Feature/pge 238 grafik zu taglichen stromkosten
pgenergy/energyleaf pull request #140
Opened 2024-07-19 09:40 UTC by hannokue

![image](https://github.com/user-attachments/assets/1251fb50-d605-4d4d-bdf4-d5e2b4f9d8af)

2024-07-19 20:12 UTC, hannokue commented
Musste pnpm install --frozen-lockfile=false ausführen, da sonst der Build fehlschlägt. Daher die vielen Veränderungen in pnpm-lock.yaml

2024-07-19 21:09 UTC, lhoeke commented on apps/web/src/components/costs/energy-costs-bar-chart.tsx
> +                        <BarChart data={data}>
Würde noch Achsenbeschriftungen hinzufügen mit <XAxis label="Datum"/> und <YAxis label="Kosten in €/>

2024-07-19 21:10 UTC, lhoeke commented on apps/web/src/app/(site)/costs/client-page.tsx
> +            <section>
Würde das Chart noch in eine Card packen. So haben Malte und Daniel das auch gemacht

2024-07-20 09:03 UTC, Big0x44 requested changes

2024-07-20 09:03 UTC, Big0x44 commented on apps/web/src/components/costs/energy-costs-bar-chart.tsx
> +        color: "#8884d8",
Finde das blau ehrlich gesagt nicht so schön. Besser wäre es, wenn du das grün verwendest, was bei den anderen Charts auch schon benutzt wird. Vorteil wäre dann auch, dass das im Theme mit drin ist

2024-07-20 09:03 UTC, Big0x44 commented on apps/web/src/components/costs/energy-costs-bar-chart.tsx
Das solltest du meiner Meinung dahin verschieben, wo auch das andere chart ist (ich glaube im UI-Package). Dann brauchst du auch nicht recharts auf der Hauptebene neu importieren

2024-07-20 09:03 UTC, Big0x44 commented on package.json
> +		"recharts": "^2.12.7",
Das sollte meiner Meinung nicht auf der Hauptebene passieren. Entweder in apps/web installieren oder das Chart selbst verschieben (s. https://github.com/pgenergy/energyleaf/pull/140/files#r1685328263)

2024-07-20 13:35 UTC, m43i commented on apps/web/src/app/(site)/costs/client-page.tsx
Auf keinen Fall machen!
Jeder Component im Tree ist dadruch eine Client Component. Dadurch werden die Server Fetches alle an den Client exposed sowie die Credentials.

Client Components sollte immer auf der untersten Ebene sein.

2024-07-20 13:42 UTC, m43i commented
> Musste pnpm install --frozen-lockfile=false ausführen, da sonst der Build fehlschlägt. Daher die vielen Veränderungen in pnpm-lock.yaml

Ist deine PNPM Version aktuell?

2024-07-21 14:25 UTC, hannokue commented
> > Musste pnpm install --frozen-lockfile=false ausführen, da sonst der Build fehlschlägt. Daher die vielen Veränderungen in pnpm-lock.yaml
> 
> Ist deine PNPM Version aktuell?

Jetzt ja 😅

2024-07-21 14:41 UTC, Big0x44 requested changes
Du hast glaube ich einige Changes von @m43i reverted. Am besten nochmal prüfen 😄

2024-07-21 14:41 UTC, Big0x44 commented on packages/ui/src/ui/chart.tsx
> +                    "flex aspect-video justify-center text-xs [&_.recharts-cartesian-axis-tick_text]:fill-muted-foreground [&_.recharts-radial-bar-background-sector]:fill-muted [&_.recharts-rectangle
Waren das nicht die Sachen, die @m43i angepasst hat?

2024-07-21 15:10 UTC, Big0x44 approved these changes

2024-07-21 15:13 UTC, lhoeke approved these changes

2024-07-21 15:13 UTC, merged