Balkonkraftwerk
pgenergy/energyleaf pull request #144
Opened 2024-07-22 15:37 UTC by randomC0der

Solaranlagen, die man z. B. auf Amazon kaufen kann, haben bereits eine Wattangabe, was es deutlich einfacher macht. Es gibt andere Rechner, die mehr Faktoren als nur Sonnenintensität berücksichtigen, (z.B. https://www.pv-berechnung.de/) habe aber nicht deren Formeln gefunden. Tatsächlich bietet diese Seite ein Javascript Snippet an, um das bei sich einzubetten, aber nein (vgl. z.B. Polyfill io warum das keine gute Idee ist).

Als Wetter API wird BrightSky verwendet, was ein Wrapper für die DWD Daten sind und OpenStreetMap für das Nachschlagen der Adresse in Koordinaten.

Das ganze sieht so aus: 

![image](https://github.com/user-attachments/assets/be72a881-a0f7-4bc8-b33b-eceba40f059f)

2024-07-22 15:55 UTC, Big0x44 requested changes

2024-07-22 16:53 UTC, m43i commented on apps/admin/src/app/(api)/api/v1/solar/route.ts
> +export const POST = async (req: NextRequest) => {
Ihr werdet CORS Erros bekommen wenn ihr den Post von Web App zu Admin App macht.
Besser wäre wahrscheinlich das alles als Server Action in der WebApp

2024-07-23 17:53 UTC, Big0x44 approved these changes

2024-07-23 17:53 UTC, Big0x44 commented on apps/web/src/actions/solar.ts
> +        const { lat, lon, display_name } = await lookupLocation(dbuser.address);
```suggestion
        const { lat, lon, displayName } = await lookupLocation(dbuser.address);
```

2024-07-23 20:20 UTC, randomC0der commented on apps/web/src/actions/solar.ts
> +        const { lat, lon, display_name } = await lookupLocation(dbuser.address);
Nein, das kommt von der OpenStreetMap API

2024-07-24 05:44 UTC, Big0x44 commented on apps/web/src/actions/solar.ts
> +        const { lat, lon, display_name } = await lookupLocation(dbuser.address);
Dann halt so
```suggestion
        const { lat, lon, display_name: displayName } = await lookupLocation(dbuser.address);
```

2024-07-24 09:17 UTC, m43i approved these changes

2024-07-24 11:47 UTC, merged

2024-07-24 20:34 UTC, RogerLithmus commented on apps/web/src/actions/solar.ts
> +        const message = success ? "" : "Es wurde kein Preis hinterlegt";
Ich weiß, ist doof weil der PR schon gemergt ist. Aber es wäre sinnvoll hier noch ein Logging einzubauen für den Erfolgsfall, damit wir wissen, dass der Nutzer mit der Funktion interagiert hat.

2024-07-25 17:40 UTC, Big0x44 commented on apps/web/src/actions/solar.ts
> +        const message = success ? "" : "Es wurde kein Preis hinterlegt";
Implementier das einfach fix auf deinem Branch für die Berichtsseite