Peaks zur Klassifizierung an die ML-API senden, klassifizierte Geräte verarbeiten und anzeigen
pgenergy/energyleaf pull request #169
Opened 2024-08-26 18:11 UTC by hannokue

2024-08-26 19:18 UTC, lhoeke commented on apps/admin/src/components/users/details/user-state-form.tsx
> +                                            Gibt an ob dieser Nutzer über Prolific bezahlt wird.
Gib an, ob...

2024-08-27 08:56 UTC, Big0x44 requested changes

2024-08-27 08:56 UTC, Big0x44 commented on apps/admin/src/app/(api)/api/v1/mark_peaks/route.ts
> +                        const peaks = await getSequencesBySensor(sensorId, { start: startDate, end: endDate });
Gibt `result` nicht bereits alle Sequenzen zurück? Zumindest war das mal so :smile: 
Würde hier auf jeden Fall eine Query sparen

2024-08-27 08:56 UTC, Big0x44 commented on apps/admin/src/app/(api)/api/v1/mark_peaks/route.ts
> +                                const electricityData = await getRawEnergyForSensorInRange(
Da kommt es mitunter zu Fehlern. Das sollte nach Möglichkeit vermieden werden

2024-08-27 08:56 UTC, Big0x44 commented on apps/admin/src/components/users/details/user-state-form.tsx
> +                                            Gibt an ob dieser Nutzer über Prolific bezahlt wird.
Es wird hier ja das Feld eines Formulares erklärt und nicht direkt der Nutzer angesprochen

2024-08-27 08:56 UTC, Big0x44 commented on apps/admin/src/query/peak.ts
> +                await saveDevicesToPeak(peak.id, devicesToSave, userId);
Wenn ich den Code richtig verstehe, sind die automatisiert zugewiesenen Geräte doch gar nicht in der DB gespeichert, oder?

2024-08-27 08:56 UTC, Big0x44 commented on apps/admin/src/query/peak.ts
> +            await saveDeviceToPeakDb(peakId, device.name, userId);
Hier sollte es meiner Meinung nach eine DB-Methode geben, die mehrere Geräte entgegennimmt, sodass das Speichern der Geräte für einen Peak in einer Transaktion durchgeführt wird

2024-08-27 08:56 UTC, Big0x44 commented on apps/web/src/components/devices/devices-overview-card.tsx
> +                                    Geräte erkennen und überwachen. Falls Sie jedoch eines dieser Geräte nicht besitzen,
> überwachen

Kann die KI das wirklich überwachen? Meines Wissensstands ist das eher ein Erkennen, oder nicht?

2024-08-27 08:56 UTC, Big0x44 commented on packages/db/src/query/device.ts
> +    const existingDevices = await getDevicesByUser(userId);
Die ganze Funktion sollte ein eine Transaktion gepackt werden

2024-08-27 08:56 UTC, Big0x44 commented on packages/db/src/query/device.ts
> +    const deletedDevices = await db.select().from(deviceHistory).where(eq(deviceHistory.userId, userId));
Eigentlich werden auch bei Änderungen Einträge in die deviceHistory Tabelle geschrieben. Es kann also sein, dass da ein noch existentes Gerät drin steht. In dem Fall funktioniert die Logik nicht

2024-08-27 08:56 UTC, Big0x44 commented on packages/db/src/query/device.ts
> +    const standardDevices = [
Finde ich ein bisschen unschön. Die Standard-Geräte werden ja durch die ML-API vorgegeben. Das ist hier aber fest im DB-Package verankert. Eigentlich sollte im Code, der sich mit der ML-API beschäftigt, festgelegt werden, was die Standard-Geräte sind.

2024-08-27 08:56 UTC, Big0x44 commented on packages/db/src/query/device.ts
> +export async function createStandardDevicesIfNotExist(userId: string) {
Ich habe ein Problem mit dieser Methode: Sie funktioniert nicht, wenn ich bereits ein Gerät mit einer der Geräte-Kategorien angelegt habe, das aber nicht den Standard-Namen hat. Z. B. eine Waschmaschine, die ich "Meine tolle Waschmaschine" nenne.
Wäre es nicht besser, das evtl. eher über die Geräte-Kategorie zu machen?

2024-08-27 08:56 UTC, Big0x44 commented on packages/db/src/query/device.ts
> +        const existingAssignments = await db
Die Performance ist hier nicht so toll (gerade mit vielen Peaks). Besser wäre aus meiner Sicht, einen Inner Join durchzuführen.

In SQL also:
``` SQL
SELECT DISTINCT sensor_data_sequence.id  FROM sensor_data_sequence
INNER JOIN deviceToPeak ON deviceToPeak.sensor_data_sequence_id = sensor_data_sequence.id
WHERE sensor_data_sequence.id IN (1, 2, 3, 4)
```
Hinweis: 1,2,3,4 sind hier die peak IDs, die man reingegeben hat.

Dann hat man alle zugewiesenen Peaks. Dann kann man in SQL noch ein Mengen-Differenz bilden, um die eigentlich gewollten Peaks zu kriegen (hier der Einfachheit halber weggelassen)

Ich weiß leider nicht, wie man das ganze mit Drizzle macht, müsste man dann schauen

2024-08-30 14:16 UTC, lhoeke approved these changes

2024-08-31 13:32 UTC, m43i approved these changes

2024-08-31 14:16 UTC, Big0x44 approved these changes

2024-08-31 14:22 UTC, merged