Postgres
pgenergy/energyleaf pull request #170
Opened 2024-08-28 11:49 UTC by m43i

2024-08-28 13:34 UTC, SlepiK requested changes

2024-08-28 13:34 UTC, SlepiK commented on packages/postgres/src/query/energy-insert.ts
> +            (valueOut < lastEntry.valueOut || valueOut - lastEntry.valueOut > timeDiff * 2)
Sind die > und < korrekt? Sollten ja die absoluten Werte sein oder nicht? Kann mich gerade auch irren.

2024-08-28 13:45 UTC, m43i commented on packages/postgres/src/query/energy-insert.ts
> +            (valueOut < lastEntry.valueOut || valueOut - lastEntry.valueOut > timeDiff * 2)
valueOut < lastEntry.valueOut: verhindert das der neue Wert geringer als der letzte ist.
valueOut - lastEntry.valueOut > timeDiff * 2: Verhindert das der Wert über dem threshold liegt und gigantisch hoch ist.

Sollte so passen um falsche gelesene Werte zu korrigieren.

2024-08-28 13:54 UTC, SlepiK commented on packages/postgres/src/query/energy-insert.ts
> +            (valueOut < lastEntry.valueOut || valueOut - lastEntry.valueOut > timeDiff * 2)
ah stimmt, habe irgendwie übersehen das du im zutreffenden Falle, valueOut auf valueOut vom lastEntry dann setzt. Also alles fine.

2024-08-28 13:55 UTC, SlepiK submitted a review, later dismissed

2024-08-28 14:59 UTC, SlepiK submitted a review, later dismissed

2024-08-29 06:03 UTC, Big0x44 commented on packages/postgres/src/types/types.ts
> +export enum DeviceCategory {
`DeviceCategory` und `SensorType` müssen ja eigentlich nicht kopiert werden

2024-08-29 06:03 UTC, Big0x44 commented on scripts/insert-energy-data.ts
> +// import db, { genId } from "@energyleaf/db";
```suggestion
```

2024-08-29 06:03 UTC, Big0x44 commented on scripts/insert-energy-data.ts
> +// import { sensorData } from "@energyleaf/db/schema";
```suggestion
```

2024-08-29 10:01 UTC, Big0x44 approved these changes

2024-08-29 10:39 UTC, SlepiK approved these changes

2024-08-29 10:39 UTC, merged