Feature/pge 33 berichtsfunktion einrichten von wochentlichen e mails
pgenergy/energyleaf pull request #38
Opened 2024-02-21 13:22 UTC by RogerLithmus

2024-02-23 06:35 UTC, Big0x44 requested changes
Du hast jetzt die ganze Logik zum Ermitteln der User, an die ein Bericht geschickt werden muss, und zum Senden der eigentlichen Mails in der Web-App umgesetzt. Das ist aber eigentlich eher was, was im Bereich der Admin-App zu verorten ist. Meienr Meinung nach sollte der Code also in die Admin-App kopiert werden.

2024-02-23 06:35 UTC, Big0x44 commented on apps/web/src/components/profile/interval-selector.tsx
> +export default function IntervalSelector({field}) {
Hier wäre es sinnvoll, den Typen von field noch zu definieren. Außerdem kannst du Field hier auch direkt übergeben, wenn du keine anderen Parameter hast.
```suggestion
export default function IntervalSelector(field) {
```

2024-02-23 06:35 UTC, Big0x44 commented on apps/web/src/components/profile/time-selector.tsx
> +export default function TimeSelector({field}) {
s. https://github.com/pgenergy/energyleaf/pull/38/files#r1500253331

2024-02-23 06:35 UTC, Big0x44 commented on apps/web/src/lib/schema/profile.ts
> +        .positive({message: "Bitte geben Sie ein gültiges Intervall an."})
Eine genaue Differenzierung der Fehlermeldungen fände ich hier besser, Also in dieser Zeile sowas wie "Bitte geben Sie einen positiven Wert für das Intervall an" und dann in der nächsten "Bitte geben Sie einen Wert kleiner oder gleich 7 für das Intervall an".
Für time dann auch

2024-03-11 13:54 UTC, RogerLithmus commented on packages/db/src/query/user.ts
> +    return db.update(user).set(data).where(eq(user.id, id));
Das war redundant vorher, ist also an der Stelle nicht notwendig und machen wir auch sonst nicht. Gibt ne Warning in der IDE

2024-03-11 13:58 UTC, RogerLithmus commented on apps/web/src/components/profile/time-selector.tsx
> +                {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23].map((possibleValues) => (
Die Syntax erlaubt der in unserem Projekt wegen der Target Version nicht, ich würde das einfach so lassen tut ja niemandem weh :D

2024-03-11 14:14 UTC, Big0x44 requested changes

2024-03-11 14:14 UTC, Big0x44 commented on apps/web/src/app/(site)/profile/page.tsx
> +            <BaseInformationForm email={session.user.email} username={session.user.name}/>
```suggestion
            <BaseInformationForm disabled={isDemo} email={session.user.email} username={session.user.name} />
```

2024-03-11 14:14 UTC, Big0x44 commented on apps/web/src/components/profile/interval-selector.tsx
> +                <SelectItem key={possibleValues} value={possibleValues.toString()}>
Wenn man das HTML hier einrückt, ist das aus meiner Sicht besser lesbar

2024-03-11 14:14 UTC, Big0x44 commented on apps/web/src/components/profile/interval-selector.tsx
> +    let returnValue = "";
Nur ne Kleinigkeit, aber ich würde die Variable entfernen und immer direkt returnen

2024-03-11 14:14 UTC, Big0x44 commented on apps/web/src/components/profile/mail-settings-form.tsx
> +
```suggestion
```

2024-03-11 14:14 UTC, Big0x44 commented on packages/db/src/query/user.ts
> + * if the current date is equal to the last report date + interval and the current time is greater than the report time
Wieder nur ne Kleinigkeit, aber die Beschreibung wäre nicht gut zu lesen, wenn man in der IDE über die Methode hovert. Da sollten mindestens Punkte drin sein und am besten auch Zeilenumbrüche (mit </br>)

2024-03-11 14:14 UTC, Big0x44 commented on packages/db/src/schema/user.ts
> +
```suggestion
```

2024-03-11 14:14 UTC, Big0x44 commented on packages/db/src/schema/user.ts
> +export const reports = mysqlTable("reports", {
Vllt sollten wir für die reports Tabelle auch noch eine History-Tabelle anlegen (wie für user_data). Dann können wir im Nachhinein sehen, ob und warum die Einstellungen von Benutzern geändert wurden.

2024-03-11 14:33 UTC, randomC0der approved these changes

2024-03-11 16:39 UTC, Big0x44 commented on packages/db/src/schema/user.ts
> +export const reports = mysqlTable("reports", {
Doch, das gehört in die DB, damit wir das später vernünftig auswerten können. Für andere Tabellen (z. B. user_data und devices) wird das ja auch so gemacht

2024-03-26 11:29 UTC, Big0x44 requested changes

2024-03-26 11:29 UTC, Big0x44 commented on packages/db/src/query/user.ts
> +            throw new Error("History data not found");
Das ist unnötig. newHistoryReports wird immer mindestens ein Tupel enthalten, weil du das oben doch hinzufügst (Z. 142) und du eine Transaktion verwendest

2024-03-26 11:29 UTC, Big0x44 commented on packages/db/src/query/user.ts
> +        await db
```suggestion
        await trx
```

2024-03-26 12:48 UTC, Big0x44 approved these changes

2024-03-26 12:48 UTC, Big0x44 commented on packages/db/src/query/user.ts
> +        const newHistoryReports = await trx
Raus

2024-03-26 13:32 UTC, merged