PGE-137: Fix bug in user select
pgenergy/energyleaf pull request #54
Opened 2024-03-11 22:17 UTC by m43i

2024-03-12 06:48 UTC, Big0x44 approved these changes

2024-03-12 12:37 UTC, Big0x44 requested changes

2024-03-12 13:23 UTC, m43i commented on apps/admin/src/components/users/user-delete-dialog.tsx
> +    const context = useUserDetailsContext();
Guter Punkt, hatte ich nicht bedacht. Ich werde das in einem Context zusammenfassen, da diese sich sehr ähnlich sind.

2024-03-19 15:44 UTC, lhoeke approved these changes

2024-03-19 22:44 UTC, merged