Feature/pge 129 dashboard verbesserung der darstellung der zeitraume auf der x achse
pgenergy/energyleaf pull request #59
Opened 2024-03-22 11:40 UTC by hannokue

Die x-Achse wird jetzt sinnvoller und übersichtlicher beschriftet, indem die Zeiträume je nach ausgewählter Zeitspanne in vollständigen Stunden oder Tagen dargestellt werden.

Hier einmal ein paar Beispiel, wie die Zeiträume jetzt dargestellt werden:

Ein Tag:
![1-tag](https://github.com/pgenergy/energyleaf/assets/147524735/88584152-9329-4d58-9c9d-f70739c29b0b)

Eine Woche:
![1-woche](https://github.com/pgenergy/energyleaf/assets/147524735/b1c7fa5f-3e50-43ab-b019-71dc31c501d6)

Ein Monat:
![1-monat](https://github.com/pgenergy/energyleaf/assets/147524735/9cac0034-032a-4aaf-8ec7-6af4eb0c6043)

2024-03-26 06:36 UTC, Big0x44 requested changes
Hast du das Chart auch so angepasst, dass die Abstände zwischen den Datensätzen jetzt korrekt ist? Vorher war das ja so, dass die Abstände zwischen zwei Datenpunkten im Chart immer gleich waren, unabhängig davon, ob da jetzt z. B. eine Stunde oder sogar ein Monat zwischen liegt

2024-03-26 06:36 UTC, Big0x44 commented on packages/ui/src/components/charts/energy-consumption/energy-consumption-chart.tsx
> +            xAxes={{ dataKey: "timestamp" }}
Das sollte am besten drin bleiben
```suggestion
                        xAxes={{ dataKey: "timestamp", name: "Vergangene Zeit " + computeTimestampLabel(aggregation, false) }}
```

2024-03-26 06:36 UTC, Big0x44 commented on packages/ui/src/components/charts/line-chart.tsx
> +        const dateInterval = Math.max(1, Math.ceil(diffDays / 20));
Was bewirkt diese magic number 20 hier? Mir erschließt sich nicht, wo dieser Wert herkommt

2024-03-27 14:08 UTC, hannokue commented on packages/ui/src/components/charts/line-chart.tsx
> +        const dateInterval = Math.max(1, Math.ceil(diffDays / 20));
Die 20 begrenzt die Anzahl der Datenpunkte auf höchstens 20, um die Lesbarkeit der x-Achse zu gewährleisten. Es werden also höchstens 20 Zeitangaben angezeigt, damit die X-Achse nicht überladen wird. Hab da bisschen ausprobiert und so ist es meiner Meinung nach am übersichtlichsten.

2024-03-27 14:09 UTC, hannokue commented on packages/ui/src/components/charts/energy-consumption/energy-consumption-chart.tsx
> +            xAxes={{ dataKey: "timestamp" }}
Kann ich auch gerne wieder reinnehmen aber fand es irgendiwe unübersichtlich

2024-04-02 05:18 UTC, Big0x44 commented on packages/ui/src/components/charts/line-chart.tsx
> +        const dateInterval = Math.max(1, Math.ceil(diffDays / 20));
Ok, magst du das vllt als Kommentar im Code ergänzen?

2024-04-12 08:47 UTC, Big0x44 approved these changes

2024-04-17 15:11 UTC, randomC0der approved these changes

2024-04-18 13:10 UTC, merged