PGE-133: SEO optimierung
pgenergy/energyleaf pull request #65
Opened 2024-04-04 16:25 UTC by m43i

2024-04-07 16:14 UTC, hannokue approved these changes

2024-04-09 09:02 UTC, Big0x44 requested changes

2024-04-09 09:02 UTC, Big0x44 commented on apps/web/src/app/layout.tsx
> +        url: "https://energyleaf.de",
Kann man die URL vllt aus der env auslesen? Sonst müsste man ja den Quellcode anpassen, wenn man die Domain ändert

2024-04-09 09:02 UTC, Big0x44 commented on apps/web/src/app/layout.tsx
> +            "Mit diesem Tool können Sie Ihren Stromverbrauch übersichtlich darstellen und besser verstehen. Analysieren Sie Ihren Verbrauch, finden Sie Einsparpotenziale und senken Sie Ihre Kosten.",
Die Beschreibung sollte man vllt noch in eine Konstante auslagern, da die in Z. 12 ja auch genutzt wird

2024-04-09 14:15 UTC, Big0x44 approved these changes

2024-04-09 14:28 UTC, merged