Pge 31 aggregierungsfunktion fur visualisierungen
pgenergy/energyleaf pull request #8
Opened 2023-12-08 12:44 UTC by lhoeke

Führt nach Auswahl die jeweilige Aggregierung durch und updated die View entsprechend. In dem Ticket geht es erst einmal um die Aggregierung des Energieverbrauchs und das Updaten der View. Im nächsten Schritt sollten wir noch darüber sprechen, wie die Behandlung von Peaks bei der Aggregierung behandelt werden soll. Sollen die Peaks dort noch angezeigt werden, etc.? Um die Verschönerung der View (bessere Unterbringung und Design des Auswahlmenüs) sowie des LineCharts (z.B. x-Achsenbeschriftung) und Tooltips wird sich Rita anschließend an dieses Ticket kümmern.

https://github.com/pgenergy/energyleaf/assets/129761217/5d8d90a2-e89e-490a-88c5-48b4de484c22

2023-12-08 15:22 UTC, m43i requested changes
Sieht top aus sonst!

2023-12-09 17:10 UTC, randomC0der approved these changes

2023-12-09 17:10 UTC, randomC0der commented on apps/web/src/lib/aggregate-energy.ts
> +        case 'hour':
kann man das nicht zu einem enum machen? Das wäre cooler

2023-12-09 17:10 UTC, randomC0der commented on apps/web/src/lib/aggregate-energy.ts
> +            data[value].timestamp.split(' ')[1] + ' ' +
Wie bei `handleHourOption`
```suggestion
            const timestampParts = data[value].timestamp.split(' ');
            timestampParts[1] + ' ' + 
```

2023-12-09 23:00 UTC, m43i approved these changes

2023-12-09 23:02 UTC, merged