PGE-168: Fehlermeldung in Actions
pgenergy/energyleaf pull request #87
Opened 2024-05-06 13:00 UTC by m43i

2024-05-07 13:57 UTC, Big0x44 requested changes
Werden die ganzen Fehlermeldungen, die von den Actions zurückgegeben werden, direkt an den Nutzer ausgegeben? Ich habe einige Typos und Grammatikfehler angemerkt. In dem Falle sollten die behoben werden, ansonsten wäre das aus meiner Sicht nicht so wild

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/auth.ts
> +            message: "Fehler beim verifizieren des Tokens.",
```suggestion
            message: "Fehler beim Verifizieren des Tokens.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/auth.ts
> +            message: "Fehler beim ändern des Passworts.",
```suggestion
            message: "Fehler beim Ändern des Passworts.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/device.ts
> +                message: "Fehler beim erstellen des Gerätes.",
```suggestion
                message: "Fehler beim Erstellen des Gerätes.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/device.ts
> +                message: "Fehler beim speichern des Gerätes.",
```suggestion
                message: "Fehler beim Speichern des Gerätes.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/device.ts
> +                message: "Es konnte kein Geräte erstellt werden",
```suggestion
                message: "Es konnte kein Gerät erstellt werden",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/onboarding.ts
> +                message: "Sie müssen angemeldet sein um das Onboarding abzuschließen.",
```suggestion
                message: "Sie müssen angemeldet sein, um das Onboarding abzuschließen.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Es gab einen Fehler beim speichern.",
```suggestion
                message: "Es gab einen Fehler beim Speichern.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihr Profil zu bearbeiten.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihr Profil zu bearbeiten.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihr Passwort zu ändern.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihr Passwort zu ändern.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Es ist ein Fehler beim ändern der E-Mail Einstellung aufgetreten.",
```suggestion
                message: "Es ist ein Fehler beim Ändern der E-Mail Einstellung aufgetreten.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihre E-Mail Einstellungen zu ändern.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihre E-Mail Einstellungen zu ändern.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Ein Fehler beim ändern ihrer Daten ist aufgetreten.",
```suggestion
                message: "Ein Fehler beim Ändern Ihrer Daten ist aufgetreten.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihre Daten zu ändern.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihre Daten zu ändern.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Ein Fehler beim speichern ihrer Ziele ist aufgetreten.",
```suggestion
                message: "Ein Fehler beim Speichern Ihrer Ziele ist aufgetreten.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihre Ziele zu aktualisieren.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihre Ziele zu aktualisieren.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Ein Fehler beim löschen ihrers Accounts ist aufgetreten.",
```suggestion
                message: "Ein Fehler beim Löschen Ihres Accounts ist aufgetreten.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/actions/profile.ts
> +                message: "Sie müssen angemeldet sein, um ihren Account zu löschen.",
```suggestion
                message: "Sie müssen angemeldet sein, um Ihren Account zu löschen.",
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/components/auth/forgot-form.tsx
> +            throw new Error("");
Vllt sollte hier dann auch eine genaue Fehlermeldung mit in den Error gegeben werden
```suggestion
            throw new Error(res.message);
```

2024-05-07 13:57 UTC, Big0x44 commented on apps/web/src/components/auth/reset-form.tsx
> +            throw new Error("Fehler beim zurücksetzen des Passworts.");
```suggestion
            throw new Error("Fehler beim Zurücksetzen des Passworts.");
```

2024-05-07 14:01 UTC, m43i commented
> Werden die ganzen Fehlermeldungen, die von den Actions zurückgegeben werden, direkt an den Nutzer ausgegeben? Ich habe einige Typos und Grammatikfehler angemerkt. In dem Falle sollten die behoben werden, ansonsten wäre das aus meiner Sicht nicht so wild

Genau so hatte ich mir das jetzt gedacht, da wir nicht direkt einen UserNotLoggedIn Error an das Frontend übergeben können. Das wird in Production entfernt und durch einen generische Error ersetzt. So haben wir die Möglichkeit, dass der Server bestimmt was angezeigt wird in bestimmten Fällen.

2024-05-08 08:57 UTC, Big0x44 approved these changes

2024-05-08 15:37 UTC, randomC0der approved these changes

2024-05-08 17:35 UTC, merged