Feature/pge 173 Einheiten und Berechnungen anpassen
pgenergy/energyleaf pull request #92
Opened 2024-05-18 12:33 UTC by hannokue

2024-05-20 08:26 UTC, Big0x44 requested changes

2024-05-20 08:26 UTC, Big0x44 commented on packages/db/src/query/sensor.ts
> +        const timeDiffHours = (currentTimestamp.getTime() - previousTimestamp.getTime()) / (1000 * 60 * 60);
Ich weiß nicht, ob das so einfach möglich ist. Auf Wikipedia steht: "Der Zähler erfasst am Zählerpunkt die elektrische [Stromstärke](https://de.wikipedia.org/wiki/Stromst%C3%A4rke) sowie die anliegende [Wechselspannung](https://de.wikipedia.org/wiki/Wechselspannung), multipliziert deren [Augenblickswerte](https://de.wikipedia.org/wiki/Augenblickswert) vorzeichengerecht, um die [Wirkleistung](https://de.wikipedia.org/wiki/Wirkleistungsmessung) zu bestimmen, und ermittelt daraus durch zeitliche [Integration](https://de.wikipedia.org/wiki/Integralrechnung) die genutzte [Wirkenergie](https://de.wikipedia.org/wiki/Wirkenergie)."

Der Zähler hat also selbst sowas wie "Messzeiträume". Für den aktuellen Zählerstand wäre das dann ja von t2 bis currentTimestamp.getTime() und für den vorherigen von t1 bis previousTimestamp.getTime(). Dann müsste man für die Zeitdifferenz hier eigentlich ja currentTimestamp.getTime() - t1 rechnen, aber t1 haben wir gar nicht. Die berechnete Leistung wäre dann also größer als die tatsächliche Leistung.
Kann aber auch sein, dass ich einfach falsch liege. Ich spreche mal mit einigen Leuten, die ein bisschen mehr Ahnung davon haben. Wäre zwar insgesamt nicht so schlimm, da die Abweichung wohl nicht so riesig sein wird. Aber wäre ja trotzdem schön zu wissen :sweat_smile:

2024-05-20 20:33 UTC, hannokue commented on packages/db/src/query/sensor.ts
> +        const previousQuery = await db
Hab es jetzt so angepasst, dass alle Peaks in einer einzigen Abfrage abgerufen werden und nur eine zusätzliche Abfrage pro Peak ausgeführt wird, um den letzten Sensor-Datenpunkt zu ermitteln.

2024-05-21 08:39 UTC, RogerLithmus approved these changes

2024-05-24 14:26 UTC, Big0x44 commented on packages/db/src/query/sensor.ts
> +        const previousQuery = await db
Du hattest hier jetzt nichts angepasst. Gab es Probleme, an die ich nicht gedacht habe?

2024-05-26 13:25 UTC, hannokue commented on packages/db/src/query/sensor.ts
> +        const previousQuery = await db
Nee hast Recht. Habe jetzt eine Transaktion hinzugefügt.

2024-05-27 10:36 UTC, merged