Feature/pge 171 peaks mehrere gerate zuordnen
pgenergy/energyleaf pull request #93
Opened 2024-05-21 11:18 UTC by RitaTagoula

2024-05-21 17:12 UTC, m43i requested changes
Allgemein fehlen komplett die Anpassungen der Querys und der UI.
Weil eigentlich hast du nur den Main Branch genommen und ein Multiselect hinzugefügt jetzt. Den wir bereits hatten.

2024-05-21 17:12 UTC, m43i commented on apps/admin/src/app/(api)/api/v1/sensor_input/route.ts
> +
Das alles sind commits vom main.
Die brauchen wir hier nicht mehr

2024-05-21 17:12 UTC, m43i commented on packages/ui/src/ui/select.tsx
> +};
Die Funktionalität können wir bereits umsetzen und ist daher redundant.

z.B.
```tsx
export function DropdownMenuCheckboxes() {
  const [showStatusBar, setShowStatusBar] = React.useState<Checked>(true)
  const [showActivityBar, setShowActivityBar] = React.useState<Checked>(false)
  const [showPanel, setShowPanel] = React.useState<Checked>(false)
 
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">Open</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56">
        <DropdownMenuLabel>Appearance</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuCheckboxItem
          checked={showStatusBar}
          onCheckedChange={setShowStatusBar}
        >
          Status Bar
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={showActivityBar}
          onCheckedChange={setShowActivityBar}
          disabled
        >
          Activity Bar
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={showPanel}
          onCheckedChange={setShowPanel}
        >
          Panel
        </DropdownMenuCheckboxItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
```

2024-05-24 12:38 UTC, randomC0der commented on apps/admin/src/app/(api)/api/v1/sensor_input/route.ts
> +                    // we purposefully return a 404 with sensor not found, because it imetates the same behavior
```suggestion
                    // we purposefully return a 404 with sensor not found, because it imitates the same behavior
```

2024-05-24 12:38 UTC, randomC0der commented on packages/db/src/query/sensor.ts
> +        const now = new Date(new Date().toUTCString());
Ich verstehe nicht, warum das?

2024-05-25 08:58 UTC, closed without merging